var myFullName;
console.log(myFullName);
myFullName = "Prakash Gadekar";
console.log("My FullName=", myFullName);
myFullName = "Prakash Mahadev Gadekar";
console.log("My FullName=", myFullName);
var myLove = "I love only Js";
console.log("My Love=", myLove);
var firstNmae = "Prakash";
console.log("First Name=", firstNmae);
var lastName = "Gadekar";
console.log("My LastName=", lastName);
var age = "24";
console.log("age=", age);
var adress = "Sangola Dist: Solapur";
console.log("Adress=", adress);
var pinCode = "413307";
console.log("Pin Code=", pinCode);
var gender = "Male";
console.log("Gednder=", gender);
var isMarried = "Married";
console.log("Is Married=", isMarried);