const fruit_seasonal = ["Banana", "Orange","Apple", "Mango", "Water Melon"];
console.log("===========================");

console.log(`The given array is= ${fruit_seasonal}`);
console.log("================ Step 01 ===============");
let first_element= fruit_seasonal[0];
let last_element=fruit_seasonal[4];
console.log(`First element of the array= ${first_element}`);
console.log(`Last element of array= ${last_element}`);
console.log("================ Step 02 =============");
console.log(`Given string= ${fruit_seasonal}`);
fruit_seasonal.unshift("Papaya");
console.log("After adding Papaya=",fruit_seasonal);
console.log("================ Step 03 =============");
console.log(`Given string= ${fruit_seasonal}`);
fruit_seasonal.splice(4,1);
console.log("After removing Mango=",fruit_seasonal);
console.log("================ Step 04 =============");
console.log(`Given string= ${fruit_seasonal}`);
fruit_seasonal.push("PineApple");
console.log("After Adding Pineapple=",fruit_seasonal);
console.log("================ Step 05 =============");
console.log(`Given string= ${fruit_seasonal}`);
fruit_seasonal.splice(4,0,"Dragon Fruit");
console.log("After inserting Dragon Fruit=",fruit_seasonal);
console.log("================ Step 06 =============");
console.log(`Given string= ${fruit_seasonal}`);
fruit_seasonal.splice(2,1,"Kiwi");
console.log("After Adding Kiwi=",fruit_seasonal);
console.log("================ Step 07 =============");
console.log(`Given string= ${fruit_seasonal}`);
const slice_s=fruit_seasonal.slice(1,4);
console.log("Show element from index 1-4 =",slice_s);
console.log("================ Step 08 =============");
console.log(`Given string= ${fruit_seasonal}`);
const slicer=fruit_seasonal.slice(4,8);
console.log("Show Last 3 elements=",slicer);